// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tribby.Core.Handlers;

#nullable disable

namespace Tribby.Core.Migrations
{
    [DbContext(typeof(SqliteDbHandler))]
    partial class SqliteDbHandlerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");
#pragma warning restore 612, 618
        }
    }
}
